# Generated by Django 5.2.7 on 2025-10-30 10:11

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remarks', models.CharField(default='No Remarks', max_length=10000)),
                ('vehicle_no', models.CharField(max_length=100)),
                ('trailer_no', models.CharField(blank=True, max_length=100, null=True)),
                ('total_mileage', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('on_duty_start_time', models.TimeField(null=True)),
                ('off_duty', models.FloatField(default=0.0)),
                ('on_duty', models.FloatField(default=0.0)),
                ('berth', models.FloatField(default=0.0)),
                ('driving', models.FloatField(default=0.0)),
                ('current_cycle_hours', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
                ('start_location', models.CharField(max_length=200)),
                ('start_coords', models.JSONField(default=dict)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_logsheets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('long', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('location', models.CharField(max_length=255)),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('end_time', models.TimeField(default=datetime.time(0, 0))),
                ('duration', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now_add=True)),
                ('duty_status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper', 'Sleeper'), ('driving', 'Driving'), ('on_duty', 'On Duty')], max_length=20)),
                ('activity', models.TextField(blank=True, null=True)),
                ('logsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.logsheet')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_location', models.CharField(max_length=200)),
                ('pickup_location', models.CharField(max_length=200)),
                ('dropoff_location', models.CharField(max_length=200)),
                ('start_coords', models.JSONField(default=dict)),
                ('pickup_coords', models.JSONField(default=dict)),
                ('end_coords', models.JSONField(default=dict)),
                ('stops', models.JSONField(default=list)),
                ('total_mileage', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('shipper', models.CharField(max_length=255)),
                ('commodity', models.CharField(max_length=255)),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_trips', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='logsheet',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.trip'),
        ),
    ]
