# Generated by Django 5.2.7 on 2025-10-08 18:54

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver', models.CharField(max_length=100)),
                ('shipper', models.CharField(max_length=255)),
                ('commodity', models.CharField(max_length=255)),
                ('total_mileage', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('on_duty_start_time', models.TimeField(null=True)),
                ('remarks', models.CharField(default='No Remarks', max_length=10000)),
                ('off_duty', models.FloatField(default=0.0)),
                ('on_duty', models.FloatField(default=0.0)),
                ('berth', models.FloatField(default=0.0)),
                ('driving', models.FloatField(default=0.0)),
                ('vehicle_no', models.CharField(max_length=100)),
                ('current_cycle_hours', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
                ('current_location', models.CharField(max_length=200)),
                ('pickup_location', models.CharField(max_length=200)),
                ('dropoff_location', models.CharField(max_length=200)),
                ('start_coords', models.JSONField(default=dict)),
                ('pickup_coords', models.JSONField(default=dict)),
                ('end_coords', models.JSONField(default=dict)),
                ('stops', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('long', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('location', models.CharField(max_length=255)),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('end_time', models.TimeField(default=datetime.time(0, 0))),
                ('duration', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now_add=True)),
                ('duty_status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper', 'Sleeper'), ('driving', 'Driving'), ('on_duty', 'On Duty')], max_length=20)),
                ('activity', models.TextField(blank=True, null=True)),
                ('logsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.logsheet')),
            ],
        ),
    ]
