# Generated by Django 5.2.7 on 2025-10-09 15:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_logsheet_trailer_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logsheet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
