# Generated by Django 5.2.7 on 2025-10-30 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_logentry_created_at_alter_logentry_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsheet',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.trip'),
        ),
    ]
