# Generated by Django 5.2.7 on 2025-11-12 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_fleet_manager_alter_vehicle_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fleet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='fleet.fleet'),
        ),
    ]
