# Generated by Django 5.2.7 on 2025-11-12 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_vehicle_fleet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fleet',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='fuellog',
            options={'ordering': ['-logged_at']},
        ),
        migrations.AlterModelOptions(
            name='maintenancealert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vehiclestatuslog',
            options={'ordering': ['-recorded_at']},
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
